//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALSTREAM.LinearAudioPlayer.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FINALSTREAM.LinearAudioPlayer.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} / {1} 件 完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string D0001 {
            get {
                return ResourceManager.GetString("D0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ編集に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP変換に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースが１つしかないため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーディオタグ情報の更新が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーディオ情報スキャンが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP変換が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0005 {
            get {
                return ResourceManager.GetString("I0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アートワークを保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0006 {
            get {
                return ResourceManager.GetString("I0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーディオファイルを登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0007 {
            get {
                return ResourceManager.GetString("I0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q0001 {
            get {
                return ResourceManager.GetString("Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一括更新({0}件)します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q0002 {
            get {
                return ResourceManager.GetString("Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した{0}件のファイルを削除してゴミ箱に移動します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q0003 {
            get {
                return ResourceManager.GetString("Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した{0}件のアイテムをリストから削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q0004 {
            get {
                return ResourceManager.GetString("Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot;データベースからすべてのデータを削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q0005 {
            get {
                return ResourceManager.GetString("Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタイル&quot;{0}&quot;を削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q0006 {
            get {
                return ResourceManager.GetString("Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラープロファイル&quot;{0}&quot;を削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q0007 {
            get {
                return ResourceManager.GetString("Q0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生中は取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0001 {
            get {
                return ResourceManager.GetString("W0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0002 {
            get {
                return ResourceManager.GetString("W0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linearスタイルアーカイブファイルを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0003 {
            get {
                return ResourceManager.GetString("W0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   監視フォルダ、保管フォルダ、対象データベースのすべてが指定されていないため、有効にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0004 {
            get {
                return ResourceManager.GetString("W0004", resourceCulture);
            }
        }
    }
}
