//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALSTREAM.LinearAudioPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FINALSTREAM.LinearAudioPlayer.Properties.LabelResource", typeof(LabelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Album に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Album {
            get {
                return ResourceManager.GetString("grid_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Artist {
            get {
                return ResourceManager.GetString("grid_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BitRate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_BitRate {
            get {
                return ResourceManager.GetString("grid_BitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LastPlay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Date {
            get {
                return ResourceManager.GetString("grid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Genre {
            get {
                return ResourceManager.GetString("grid_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cnt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_PlayCount {
            get {
                return ResourceManager.GetString("grid_PlayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Rating {
            get {
                return ResourceManager.GetString("grid_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ★ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Selection {
            get {
                return ResourceManager.GetString("grid_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Tag {
            get {
                return ResourceManager.GetString("grid_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Time {
            get {
                return ResourceManager.GetString("grid_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Title {
            get {
                return ResourceManager.GetString("grid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Track {
            get {
                return ResourceManager.GetString("grid_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string grid_Year {
            get {
                return ResourceManager.GetString("grid_Year", resourceCulture);
            }
        }
    }
}
